name: Helm Chart Lint and Template Test

on:
  workflow_dispatch:

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0 

      - name: Lint Helm chart
        run: |
          helm lint ./myapp-chart

      - name: Template Helm chart with custom values
        run: |
          helm template testrelease ./myapp-chart \
            --set image.repository=nginx \
            --set image.tag=stable \
            --set replicaCount=3 \
            --set welcomeMessage="CI Test Message" \
            --set service.port=8080
